"""modified task table

Revision ID: 1e81bff42d85
Revises: 6f1e877f8fba
Create Date: 2026-03-10 15:54:00.697251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e81bff42d85'
down_revision: Union[str, Sequence[str], None] = '6f1e877f8fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task', sa.String(length=20), nullable=False))
    op.drop_column('tasks', 'text')
    op.drop_column('tasks', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('title', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('text', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'task')
    # ### end Alembic commands ###
